In [ ]:
!conda install pandas seaborn matplotlib

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])

In [3]:
arr_1d

array([1, 2, 3, 4, 5])

In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [10]:
nd= arr_1d.reshape((5, 1))
nd

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr_sum = arr_1d +10
arr_sum

array([11, 12, 13, 14, 15])

In [12]:
arr_product = arr_1d * 2
arr_product

array([ 2,  4,  6,  8, 10])

In [13]:
arr_bd = arr_2d +np.array([1,2,3])
arr_bd

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
#Indexing

ele = arr_1d[2]
ele

3

In [16]:
ele1 = arr_1d[4]
ele1

5

In [17]:
#slicing
#start_index : end_index-1
slice_1d = arr_1d[1:4]
slice_1d

array([2, 3, 4])

In [18]:
slice_1e = arr_1d[2:5]
slice_1e

array([3, 4, 5])

In [19]:
ele_2d = arr_2d[1,2]
ele_2d

6

In [20]:
ele_2e = arr_2d[0,1]
ele_2e

2

Session 3 Code

In [12]:
import pandas as pd
df = pd.read_csv('data.csv')
df

Customer ID         Name   Age   Income  Transaction Amount
0          101     JOHN DOE  25.0  50000.0               100.0
1          102   JANE SMITH  32.0      NaN               200.0
2          103  LINDA ADAMS  31.0  52000.0               250.0
3          104  BOB JOHNSON   NaN  60000.0               150.0
4          105    SUSAN LEE  45.0  45000.0               300.0
5          106   CHRIS WONG  29.0  55000.0                 NaN
6          107  JAMES BROWN   NaN  60000.0               400.0

In [14]:
df.head(3)

Customer ID         Name   Age   Income  Transaction Amount
0          101     JOHN DOE  25.0  50000.0               100.0
1          102   JANE SMITH  32.0      NaN               200.0
2          103  LINDA ADAMS  31.0  52000.0               250.0

In [15]:
df.tail(4)

Customer ID         Name   Age   Income  Transaction Amount
3          104  BOB JOHNSON   NaN  60000.0               150.0
4          105    SUSAN LEE  45.0  45000.0               300.0
5          106   CHRIS WONG  29.0  55000.0                 NaN
6          107  JAMES BROWN   NaN  60000.0               400.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer ID         7 non-null      int64  
 1   Name                7 non-null      object 
 2   Age                 5 non-null      float64
 3   Income              6 non-null      float64
 4   Transaction Amount  6 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 408.0+ bytes


In [17]:
data1 = {'Name':['John','Anna','Peter'], 'Age': [28,24,35]}
df1= pd.DataFrame(data1)
df1

Name  Age
0   John   28
1   Anna   24
2  Peter   35

In [18]:
names= df1['Name']
names

0     John
1     Anna
2    Peter
Name: Name, dtype: object

In [19]:
adults = df1[df1['Age']>25]
adults

Name  Age
0   John   28
2  Peter   35

In [20]:
age_mean = df1.groupby('Name')['Age'].mean()
age_mean

Name
Anna     24.0
John     28.0
Peter    35.0
Name: Age, dtype: float64

In [22]:
data_2 = {'Name': ['John','Anna'], 'City': ['New York', 'London']}
df2= pd.DataFrame(data_2)
df2

Name      City
0  John  New York
1  Anna    London

In [23]:
mdf = pd.merge(df1,df2, on="Name")
mdf

Name  Age      City
0  John   28  New York
1  Anna   24    London